### ISSUE TITLE
New property

### ISSUE THREAD

**Issue by luciano01** [mvfsillva/dialetus-service#105]
Is it possible to implement a new property of type **image** that represented the flag of each state? Can be called _flag_.
It's much better for UX to have flags in a GridView/ListView than just state names.

**Comment by mvfsillva** [comment]
@brunopulis what do you think?

**Comment by mvfsillva** [comment]
@luciano01 I like your proposal, would you like to implement? 
I have two questions: 
1. This images will be SVG type?
2. Is your project is open source?
> If yes, send me URL to put in the readme.

**Comment by brunopulis** [comment]
@mvfsillva and @luciano01 I like the idea to use flags from each state. As Marcus said it would be ideal to use SVG to represent each flag because for accessibility it is very easy to manipulate.

**Comment by mvfsillva** [comment]
What do you think @victorferreira?

**Comment by victorferreira** [comment]
That's a great idea. We could use the svg files used by Wikipedia.

https://pt.wikipedia.org/wiki/Ficheiro:Bandeira_da_Bahia.svg

**Comment by luciano01** [comment]
> @luciano01 I like your proposal, would you like to implement?
> I have two questions:
> 
> 1. This images will be SVG type?
> 2. Is your project is open source?
>    _If yes, send me the URL to put in the readme._

I don't have experience with JavaScript. Would be better someone to implement, rsrs.

Answering:

1- I think SVG is better.
2- This is my intention, but I'm recovering from surgery on my shoulder, programming with one hand. Soon as possible I will make the project available on Github.

**Comment by mvfsillva** [comment]
Nice @luciano01, I will implement :]

**Comment by brunopulis** [comment]
@mvfsillva Nice man, don't forget to describe the SVG files to improve the accessibility <3

**Comment by mvfsillva** [comment]
Ok @brunopulis help me with this

**Comment by brunopulis** [comment]
@mvfsillva for sure dude ❤️

**Comment by luciano01** [comment]
> @luciano01 I like your proposal, would you like to implement?
> I have two questions:
> 
> 1. This images will be SVG type?
> 2. Is your project is open source?
>    _If yes, send me the URL to put in the readme._

Hey @mvfsillva , I finished uploading the project on Github. But I am still updating the code and the readme. [Here's the link]( https://github.com/luciano01/app-dialetus-service)

**Comment by mvfsillva** [comment]
Hi @victorferreira thanks for the opinion, you were thinking of implementing?

**Comment by mvfsillva** [comment]
Sorry @victorferreira, I didn't ask you if you would like to implement 🙁 My bad.

**Comment by malaquiasdev** [comment]
@luciano01 Hello man!! Your link is not working, do you have another?

**Comment by luciano01** [comment]
> @luciano01 Hello man!! Your link is not working, do you have another?

Hello @malaquiasdev 
I'm working on new updates to my repositories, so I needed to take the repository out. But in the next few days, it will be online again. Thanks for asking.
New link (newly created): [luciano01/dialetus](https://github.com/luciano01/dialetus)

**Comment by luciano01** [comment]
@malaquiasdev 
The repository is online. I made some changes to the design. 
It's still in progress, check it out.
