### ISSUE TITLE
Meaning linking support

### ISSUE THREAD

**Issue by jeffersonmourak** [mvfsillva/dialetus-service#5]
# Add meaning link support

be able to link different meanings from different regions.  
E.g.
`Oxe` Abreviation from `Oxente`

Api example
```
{
    dialect: "Oxente",
    meanings: [
        "surpresa",
        "admiração"
    ],
    examples: [
        "Oxente mainha!"
    ]
},

{
    dialect: "Oxe",
    originated: "baianês.Oxente"
    examples: [
        "Oxe omi!"
    ]
},
```

**Comment by mvfsillva** [comment]
Very good, send a pull request for the project!

![](https://media.giphy.com/media/l0HUqsz2jdQYElRm0/giphy.gif)
