### ISSUE TITLE
Each word have a synonyms

### ISSUE THREAD

**Issue by emanuelgsouza** [mvfsillva/dialetus-service#82]
For each word, have a synonym section. For example: in the "Carioques" section, the word "Bolado" would have a synonymous word, "Chateado".

**Comment by mvfsillva** [comment]
I think this crazy and funny because of the Brazilian language is very rich, and a one-word may have N possibilities.

@emanuelgsouza would you like to send us a PR?

**Comment by emanuelgsouza** [comment]
Hi!

Yes, I will send a PR with my ideia from this functionality.

For now, I think the following, like this: In the dialect, add the new prop, `synonyms`. For example:

```
 {
    "dialect": "Bolado",
    "meanings": ["Quando a gente fica preocupado com algo ou com alguém ou não entendeu alguma situação."],
    "examples": ["Fiquei bolado com minha nota baixa na escola.", "Estou bolado com meu irmão."]
  }
```

will be:

```
 {
    "dialect": "Bolado",
    "meanings": ["Quando a gente fica preocupado com algo ou com alguém ou não entendeu alguma situação."],
    "examples": ["Fiquei bolado com minha nota baixa na escola.", "Estou bolado com meu irmão."],
    "synonyms": ["Chateado", "Irritado"]
  }
```

What do you think?

**Comment by mvfsillva** [comment]
Great! Please send me a pull request 🚀
